-- V3.1 row-level cost and order fact foundation.
-- Apply only through the deployment migration process after backup and acceptance.

CREATE TABLE fact_import_batches (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  fact_kind VARCHAR(16) NOT NULL,
  template_type VARCHAR(64) NOT NULL,
  city_id BIGINT NOT NULL,
  operator_user_id BIGINT NOT NULL,
  source_file_name VARCHAR(255) NOT NULL,
  source_file_sha256 VARCHAR(64) NOT NULL,
  source_file_base64 LONGTEXT NULL,
  status VARCHAR(32) NOT NULL,
  total_rows INT NOT NULL DEFAULT 0,
  success_rows INT NOT NULL DEFAULT 0,
  error_rows INT NOT NULL DEFAULT 0,
  error_summary_json JSON NULL,
  result_summary_json JSON NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fact_batch_city_kind_hash (city_id, fact_kind, source_file_sha256),
  KEY idx_fact_batch_status (status, created_at),
  CONSTRAINT fk_fact_batch_city FOREIGN KEY (city_id) REFERENCES cities (id),
  CONSTRAINT fk_fact_batch_operator FOREIGN KEY (operator_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_source_rows (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  import_batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(255) NOT NULL,
  `row_number` INT NOT NULL,
  row_hash VARCHAR(64) NOT NULL,
  business_key VARCHAR(512) NULL,
  raw_json JSON NOT NULL,
  normalized_json JSON NULL,
  status VARCHAR(32) NOT NULL,
  errors_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fact_source_batch_row (import_batch_id, sheet_name, `row_number`),
  KEY idx_fact_source_business_key (business_key),
  CONSTRAINT fk_fact_source_batch FOREIGN KEY (import_batch_id) REFERENCES fact_import_batches (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cost_facts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  city_id BIGINT NOT NULL,
  contract_id BIGINT NOT NULL,
  occurred_on DATE NOT NULL,
  period_year INT NOT NULL,
  period_month TINYINT NOT NULL,
  cost_category_code VARCHAR(50) NOT NULL,
  cost_subtype VARCHAR(100) NULL,
  description VARCHAR(1000) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  actual_spender VARCHAR(100) NULL,
  advance_payer VARCHAR(100) NULL,
  receipt_type VARCHAR(100) NULL,
  approval_number VARCHAR(100) NULL,
  approval_status VARCHAR(100) NULL,
  ding_talk_data_id VARCHAR(128) NULL,
  mileage DECIMAL(18,2) NULL,
  locations_json JSON NULL,
  attachments_json JSON NULL,
  raw_payload_json JSON NULL,
  source_type VARCHAR(64) NOT NULL,
  import_batch_id BIGINT NULL,
  source_row_id BIGINT NULL,
  reversed_fact_id BIGINT NULL,
  is_reversed TINYINT(1) NOT NULL DEFAULT 0,
  version_no INT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_cost_facts_scope_period (city_id, period_year, period_month),
  KEY idx_cost_facts_contract (contract_id),
  KEY idx_cost_facts_batch (import_batch_id),
  CONSTRAINT fk_cost_fact_city FOREIGN KEY (city_id) REFERENCES cities (id),
  CONSTRAINT fk_cost_fact_contract FOREIGN KEY (contract_id) REFERENCES contracts (id),
  CONSTRAINT fk_cost_fact_batch FOREIGN KEY (import_batch_id) REFERENCES fact_import_batches (id),
  CONSTRAINT fk_cost_fact_source_row FOREIGN KEY (source_row_id) REFERENCES fact_source_rows (id),
  CONSTRAINT fk_cost_fact_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_cost_fact_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE order_facts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  city_id BIGINT NOT NULL,
  contract_id BIGINT NOT NULL,
  purchase_order_no VARCHAR(160) NOT NULL,
  order_status VARCHAR(100) NOT NULL,
  tax_inclusive_amount DECIMAL(18,2) NOT NULL,
  material_name VARCHAR(1000) NOT NULL,
  material_code VARCHAR(160) NOT NULL,
  project_code VARCHAR(160) NULL,
  project_name VARCHAR(1000) NULL,
  site_code VARCHAR(160) NULL,
  site_name VARCHAR(1000) NULL,
  ordered_at DATETIME NOT NULL,
  period_year INT NOT NULL,
  period_month TINYINT NOT NULL,
  receipt_status VARCHAR(100) NULL,
  source_type VARCHAR(64) NOT NULL,
  import_batch_id BIGINT NULL,
  source_row_id BIGINT NULL,
  business_key VARCHAR(512) NOT NULL,
  is_reversal TINYINT(1) NOT NULL DEFAULT 0,
  is_reversed TINYINT(1) NOT NULL DEFAULT 0,
  reversed_fact_id BIGINT NULL,
  raw_payload_json JSON NULL,
  version_no INT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  updated_by BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order_fact_city_business_key (city_id, business_key),
  KEY idx_order_facts_scope_period (city_id, period_year, period_month),
  KEY idx_order_facts_contract (contract_id),
  KEY idx_order_facts_batch (import_batch_id),
  CONSTRAINT fk_order_fact_city FOREIGN KEY (city_id) REFERENCES cities (id),
  CONSTRAINT fk_order_fact_contract FOREIGN KEY (contract_id) REFERENCES contracts (id),
  CONSTRAINT fk_order_fact_batch FOREIGN KEY (import_batch_id) REFERENCES fact_import_batches (id),
  CONSTRAINT fk_order_fact_source_row FOREIGN KEY (source_row_id) REFERENCES fact_source_rows (id),
  CONSTRAINT fk_order_fact_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_order_fact_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE fact_versions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  fact_type VARCHAR(16) NOT NULL,
  fact_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  change_type VARCHAR(32) NOT NULL,
  before_data_json JSON NULL,
  after_data_json JSON NULL,
  reason VARCHAR(500) NOT NULL,
  operator_user_id BIGINT NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  import_batch_id BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_fact_version (fact_type, fact_id, version_no),
  KEY idx_fact_version_operator (operator_user_id, created_at),
  CONSTRAINT fk_fact_version_operator FOREIGN KEY (operator_user_id) REFERENCES users (id),
  CONSTRAINT fk_fact_version_batch FOREIGN KEY (import_batch_id) REFERENCES fact_import_batches (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
